# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Codecov

      uses: codecov/codecov-action@v1.1.1
      with:
        # User defined upload name. Visible in Codecov UI
        name: Lingo Project
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: fef694a8-6643-45c7-82ed-50adda621549
        # Path to coverage file to upload
        file: /codecov# optional
        # Comma-separated list of files to upload
